[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/duoan/TorchCode/blob/master/templates/04_layernorm.ipynb)

# 🟡 Medium: Implement LayerNorm

Implement **Layer Normalization** from scratch.

$$\text{LayerNorm}(x) = \gamma \cdot \frac{x - \mu}{\sqrt{\sigma^2 + \epsilon}} + \beta$$

where $\mu$ and $\sigma^2$ are computed over the **last dimension**.

### Signature
```python
def my_layer_norm(
    x: torch.Tensor,      # input
    gamma: torch.Tensor,   # scale (same size as last dim)
    beta: torch.Tensor,    # shift (same size as last dim)
    eps: float = 1e-5
) -> torch.Tensor:
    ...
```

### Rules
- Do **NOT** use `F.layer_norm` or `torch.nn.LayerNorm`
- Normalize over the last dimension only
- Must support autograd

In [2]:
# Install torch-judge in Colab (no-op in JupyterLab/Docker)
try:
    import google.colab
    get_ipython().run_line_magic('pip', 'install -q torch-judge')
except ImportError:
    pass


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 4.2 MB/s eta 0:00:00


In [3]:
import torch

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/duoan/TorchCode/blob/master/templates/04_layernorm.ipynb)

# 🟡 Medium: Implement LayerNorm

Implement **Layer Normalization** from scratch.

$$\text{LayerNorm}(x) = \gamma \cdot \frac{x - \mu}{\sqrt{\sigma^2 + \epsilon}} + \beta$$

where $\mu$ and $\sigma^2$ are computed over the **last dimension**.

### Signature
```python
def my_layer_norm(
    x: torch.Tensor,      # input
    gamma: torch.Tensor,   # scale (same size as last dim)
    beta: torch.Tensor,    # shift (same size as last dim)
    eps: float = 1e-5
) -> torch.Tensor:
    ...
```

### Rules
- Do **NOT** use `F.layer_norm` or `torch.nn.LayerNorm`
- Normalize over the last dimension only
- Must support autograd

In [8]:
x = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
x.sum(dim=0, keepdim=True)  # Sum across rows, keep dimensions

tensor([[5., 7., 9.]])

In [31]:
# ✏️ YOUR IMPLEMENTATION HERE

def my_layer_norm(x, gamma, beta, eps=1e-5):
    mean = x.mean(dim = -1, keepdims=True)
    var = x.var(dim = -1, keepdim = True, unbiased=False)
    x_hat= (x-mean)/torch.sqrt(var+eps)
    return gamma*x_hat+beta
    pass  # Replace this

Using  unbiased=False  is important because PyTorch’s LayerNorm uses the population variance, not the sample variance.

In [32]:
torch.nn.functional.layer_norm(x, [8], gamma, beta)

tensor([[ 0.1861,  0.5612, -1.6897, -1.4206,  0.4903,  0.7902,  1.3556, -0.2732],
        [ 0.2429, -1.1755,  0.8781, -1.1294,  0.6838, -1.2201,  1.5938,  0.1264]])

In [33]:
my_layer_norm(x, gamma, beta)

tensor([[ 0.1861,  0.5612, -1.6897, -1.4206,  0.4903,  0.7902,  1.3556, -0.2732],
        [ 0.2429, -1.1755,  0.8781, -1.1294,  0.6838, -1.2201,  1.5938,  0.1264]])

In [34]:
# 🧪 Debug
x = torch.randn(2, 8)
gamma = torch.ones(8)
beta = torch.zeros(8)

out = my_layer_norm(x, gamma, beta)
ref = torch.nn.functional.layer_norm(x, [8], gamma, beta)

print("Your output mean:", out.mean(dim=-1))   # should be ~0
print("Your output std: ", out.std(dim=-1))     # should be ~1
print("Match ref?      ", torch.allclose(out, ref, atol=1e-4))

Your output mean: tensor([-5.2154e-08, -1.1548e-07])
Your output std:  tensor([1.0690, 1.0690])
Match ref?       True


In [35]:
# ✅ SUBMIT
from torch_judge import check
check("layernorm")


🧪 Testing: Implement LayerNorm (Medium)
──────────────────────────────────────────────────
  ✅ [1/3] Shape and basic behavior (1.3ms)
  ✅ [2/3] With learned parameters (1.7ms)
  ✅ [3/3] Gradient flow (1.0ms)
──────────────────────────────────────────────────
  🎉 All 3 tests passed! (4.0ms total)
  Progress saved. Run status() to see your dashboard.

